import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy | Vikrshi Suppliers Pvt Ltd',
  description: 'Privacy Policy of Vikrshi Suppliers Pvt Ltd regarding customer data and WhatsApp orders.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="pt-24 pb-20 bg-cream-50 min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="py-4">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-leaf-600 hover:text-leaf-700 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Home</span>
          </Link>
        </div>

        <div className="bg-white rounded-3xl p-8 sm:p-12 border border-cream-200 shadow-2xs space-y-6 text-forest-900">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-leaf-500/10 text-leaf-500">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <h1 className="font-serif text-3xl font-bold text-forest-950">
              Privacy Policy
            </h1>
          </div>
          <p className="text-xs text-forest-700/60">
            Last Updated: October 2026 • Vikrshi Suppliers Pvt Ltd
          </p>

          <div className="space-y-4 text-xs sm:text-sm text-forest-800 leading-relaxed pt-4 border-t border-cream-100">
            <h3 className="font-serif text-lg font-bold text-forest-950">1. Information We Collect</h3>
            <p>
              Vikrshi Suppliers Pvt Ltd collects minimal information necessary to deliver farm products to your community. When you assemble a product order or send an inquiry via WhatsApp or our contact form, we receive your name, contact telephone/WhatsApp number, and delivery locality in Hyderabad or surrounding service areas.
            </p>

            <h3 className="font-serif text-lg font-bold text-forest-950">2. How We Use Your Information</h3>
            <p>
              Your contact details are used strictly for order logistics: confirming morning harvest availability, coordinating temperature-controlled dispatch with our delivery drivers, and sending seasonal harvest alerts if you have subscribed to our bulletin.
            </p>

            <h3 className="font-serif text-lg font-bold text-forest-950">3. No Sale of Customer Data</h3>
            <p>
              We respect your privacy as much as we respect soil health. We never sell, rent, or trade your personal telephone numbers or order histories to any external marketing agencies or third parties.
            </p>

            <h3 className="font-serif text-lg font-bold text-forest-950">4. WhatsApp Data Transmission</h3>
            <p>
              Our ordering system utilizes WhatsApp end-to-end encrypted messaging. The message generated by our web app is transferred directly to your native WhatsApp client to converse with our dispatch hub.
            </p>

            <h3 className="font-serif text-lg font-bold text-forest-950">5. Contact Our Data Officer</h3>
            <p>
              If you have any questions regarding your delivery records or wish to update your details, contact info@vikrshi.com or write to our Shamshabad hub.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
