import { CompanySettings, LocationItem, Category, Product, CustomerReview } from '@/types';

export const initialCompanySettings: CompanySettings = {
  companyName: 'Vikrshi Suppliers Pvt Ltd',
  legalName: 'Vikrshi Suppliers Private Limited',
  tagline: 'Fresh From Our Farms, Naturally Yours.',
  shortDescription: 'Responsibly grown organic vegetables, crisp leafy greens, and sun-ripened fruits delivered directly from certified partner farms to your doorstep.',
  logoUrl: '/logo.png',
  whatsappNumber: '919490123456',
  whatsappDisplay: '+91 94901 23456',
  email: 'hello@vikrshi.com',
  phone: '+91 94901 23456',
  instagramUrl: 'https://instagram.com/vikrshi.farms',
  instagramHandle: '@vikrshi.farms',
  address: {
    line1: 'Survey No. 42, Green Belt Agri Park',
    line2: 'Shamshabad Agro Corridor',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500077',
    country: 'India',
  },
  businessHours: {
    weekdays: '6:00 AM – 8:30 PM',
    weekends: '6:00 AM – 9:00 PM',
    deliverySlots: [
      'Morning Harvest Batch: 6:30 AM – 9:30 AM',
      'Evening Farm Batch: 4:30 PM – 7:30 PM',
    ],
  },
  orderingEnabled: true,
  defaultLocation: 'Hyderabad',
};

export const initialLocations: LocationItem[] = [
  {
    id: 'loc-hyd',
    cityName: 'Hyderabad',
    state: 'Telangana',
    slug: 'hyderabad',
    isActive: true,
    isDefault: true,
    deliveryAvailability: 'Same-Day Delivery',
    deliveryAreas: [
      'Jubilee Hills',
      'Banjara Hills',
      'Gachibowli',
      'Madhapur',
      'Hitec City',
      'Kondapur',
      'Kukatpally',
      'Manikonda',
      'Financial District',
      'Tellapur',
      'Begumpet',
      'Somajiguda',
      'Attapur',
      'Kokapet',
    ],
    hubAddress: 'Vikrshi Central Sorting Hub, Shamshabad Agro Park, Hyderabad - 500077',
    contactPhone: '+91 94901 23456',
    operatingHours: '5:30 AM – 8:30 PM Everyday',
    pincodes: ['500033', '500034', '500081', '500084', '500032', '500072', '500089', '500075', '500016', '500077'],
  },
  {
    id: 'loc-sec',
    cityName: 'Secunderabad',
    state: 'Telangana',
    slug: 'secunderabad',
    isActive: true,
    isDefault: false,
    deliveryAvailability: 'Same-Day Delivery',
    deliveryAreas: [
      'West Marredpally',
      'East Marredpally',
      'Sainikpuri',
      'Alwal',
      'Trimulgherry',
      'Tarnaka',
      'Karkhana',
      'Bowenpally',
    ],
    hubAddress: 'Vikrshi North Depot, Near Sainikpuri Crossroads, Secunderabad - 500094',
    contactPhone: '+91 94901 23457',
    operatingHours: '6:00 AM – 8:00 PM Everyday',
    pincodes: ['500026', '500015', '500094', '500010', '500009', '500017'],
  },
  {
    id: 'loc-wgl',
    cityName: 'Warangal',
    state: 'Telangana',
    slug: 'warangal',
    isActive: true,
    isDefault: false,
    deliveryAvailability: 'Next-Day Morning',
    deliveryAreas: ['Hanamkonda', 'Kazipet', 'Subedari', 'Nayeem Nagar', 'Hunter Road'],
    hubAddress: 'Vikrshi Warangal Regional Center, Hanamkonda - 506001',
    contactPhone: '+91 94901 23458',
    operatingHours: '7:00 AM – 7:00 PM Mon-Sat',
    pincodes: ['506001', '506002', '506004'],
  },
  {
    id: 'loc-blr',
    cityName: 'Bengaluru',
    state: 'Karnataka',
    slug: 'bengaluru',
    isActive: false,
    isDefault: false,
    deliveryAvailability: 'Coming Soon',
    deliveryAreas: ['Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield', 'Bellandur'],
    hubAddress: 'South Hub 2 (Upcoming), Sarjapur Road, Bengaluru',
    contactPhone: '+91 94901 23456',
    operatingHours: 'Launching Soon',
    pincodes: ['560034', '560038', '560102'],
  },
  {
    id: 'loc-vjw',
    cityName: 'Vijayawada',
    state: 'Andhra Pradesh',
    slug: 'vijayawada',
    isActive: false,
    isDefault: false,
    deliveryAvailability: 'Coming Soon',
    deliveryAreas: ['Benz Circle', 'Labbipet', 'Patamata', 'Governorpet'],
    hubAddress: 'Krishna Delta Hub (Upcoming), Vijayawada',
    contactPhone: '+91 94901 23456',
    operatingHours: 'Launching Soon',
    pincodes: ['520010', '520008'],
  },
];

export const initialCategories: Category[] = [
  {
    id: 'cat-veg',
    slug: 'vegetables',
    name: 'Fresh Vegetables',
    description: 'Crisp, earthy root vegetables and tender nightshades harvested daily at peak ripeness.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    itemCount: 1,
    accentColor: '#2D6A4F',
  },
  {
    id: 'cat-fruits',
    slug: 'fruits',
    name: 'Fresh Fruits',
    description: 'Sweet, sun-kissed orchard fruits hand-picked without artificial wax or chemical accelerators.',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=800&q=80',
    itemCount: 1,
    accentColor: '#F4A261',
  },
  {
    id: 'cat-greens',
    slug: 'greens',
    name: 'Leafy Greens',
    description: 'Tender spinach, methi, mint, and cilantro washed in pure spring water and packed chilled.',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
    itemCount: 1,
    accentColor: '#52B788',
  },
  {
    id: 'cat-seasonal',
    slug: 'seasonal',
    name: 'Seasonal Produce',
    description: 'Limited-harvest specialty produce grown strictly in harmony with seasonal sun cycles.',
    image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=800&q=80',
    itemCount: 0,
    accentColor: '#E76F51',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-tomato',
    name: 'Organic Country Tomatoes (Naatu Tomato)',
    slug: 'organic-country-tomatoes',
    category: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shortDescription: 'Tangy, juicy heirloom country tomatoes grown with compost-enriched red soil.',
    description: 'Harvested at daybreak in Vikrshi’s Vikarabad partner farms. These Naatu tomatoes boast a rich umami tartness, thin skin, and deep red flesh unblemished by synthetic ripening gas.',
    price: 45,
    originalPrice: 55,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: false,
    harvestDate: 'Morning Harvest (Today)',
    originLocation: 'Vikarabad Valley, Telangana',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Rich in Lycopene', 'High Vitamin C', 'Potassium & Folate'],
    farmingMethod: 'Jeevamerutham soil dressing & open-pollinated heirloom seeds',
    shelfLife: '4–5 days at room temperature',
  },
  {
    id: 'prod-spinach',
    name: 'Tender Baby Palak (Spinach)',
    slug: 'tender-baby-palak-spinach',
    category: 'greens',
    categoryName: 'Leafy Greens',
    shortDescription: 'Crisp emerald leaves brimming with dietary iron and natural sweetness.',
    description: 'Grown on raised beds using slow-drip natural spring irrigation. Cleaned carefully to remove silt, ready to enrich your dals, smoothies, and saag preparations.',
    price: 30,
    originalPrice: 38,
    unit: '1 bunch (~250g)',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: false,
    harvestDate: 'Harvested 5:00 AM Today',
    originLocation: 'Chevella Farms, Telangana',
    availableLocations: ['hyderabad', 'secunderabad'],
    nutritionalHighlights: ['Dietary Iron', 'Vitamin K & A', 'Zero Chemical Residue'],
    farmingMethod: 'Natural composting & neem oil pest deterrence',
    shelfLife: '3–4 days chilled',
  },
  {
    id: 'prod-carrots',
    name: 'Crunchy Ooty Carrots',
    slug: 'crunchy-ooty-carrots',
    category: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shortDescription: 'Sweet, vibrant highland carrots packed with natural beta-carotene.',
    description: 'Grown in high-altitude organic plots in the Nilgiri hills. Their natural sweetness and satisfying crunch make them ideal for salads, fresh juicing, or traditional halwa.',
    price: 68,
    originalPrice: 85,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: false,
    harvestDate: 'Fresh Dispatch Yesterday Evening',
    originLocation: 'Nilgiri High Valley, Sourced directly',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Beta-Carotene', 'Fiber Rich', 'Eye Health Booster'],
    farmingMethod: 'Mountain terrace organic farming',
    shelfLife: '7–10 days in cold storage',
  },
  {
    id: 'prod-bell-peppers',
    name: 'Farm-Fresh Tricolor Bell Peppers',
    slug: 'tricolor-bell-peppers',
    category: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shortDescription: 'Crisp red, yellow, and green capsicums harvested with delicate stem intact.',
    description: 'Naturally sheltered polyhouse produce grown under strict climate controls without synthetic sprays. Delivers a vibrant crunch and subtle peppery sweetness.',
    price: 85,
    originalPrice: 110,
    unit: '500g (Pack of 3)',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Harvested Today',
    originLocation: 'Medak Polyhouse Collective, Telangana',
    availableLocations: ['hyderabad', 'secunderabad'],
    nutritionalHighlights: ['300% Daily Vitamin C', 'Antioxidants', 'Low Calorie'],
    farmingMethod: 'Biological pest management (ladybug release)',
    shelfLife: '6–8 days refrigerated',
  },
  {
    id: 'prod-pomegranate',
    name: 'Ruby Red Organic Pomegranate (Anar)',
    slug: 'ruby-red-organic-pomegranate',
    category: 'fruits',
    categoryName: 'Fresh Fruits',
    shortDescription: 'Deep ruby arils bursting with sweet-tart juice and powerful antioxidants.',
    description: 'Cultivated in the mineral-rich arid orchards of Mahabubnagar. Tree-ripened to ensure optimal polyphenol concentration and soft, edible seeds.',
    price: 160,
    originalPrice: 190,
    unit: '1 kg (~3-4 fruits)',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: false,
    harvestDate: 'Picked 2 Days Ago',
    originLocation: 'Mahabubnagar Orchards, Telangana',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Punicalagins Antioxidant', 'Heart Health', 'Anti-inflammatory'],
    farmingMethod: 'Cow-dung manure & micro-sprinkler fertigation',
    shelfLife: '12–15 days',
  },
  {
    id: 'prod-sitaphal',
    name: 'Forest Custard Apple (Wild Sitaphal)',
    slug: 'forest-custard-apple-sitaphal',
    category: 'seasonal',
    categoryName: 'Seasonal Produce',
    shortDescription: 'Creamy, fragrant autumn delicacy harvested from wild Deccan scrub forests.',
    description: 'Gathered by tribal farmer collectives across the Ananthagiri hills. Unmatched floral aroma and decadent velvety sweetness, ripened naturally without calcium carbide.',
    price: 120,
    originalPrice: 145,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: true,
    harvestDate: 'Fresh Morning Forage',
    originLocation: 'Ananthagiri Hill Forest Tracts, Telangana',
    availableLocations: ['hyderabad', 'secunderabad'],
    nutritionalHighlights: ['Magnesium & Potassium', 'Natural Energy', 'Immunity Boost'],
    farmingMethod: 'Wild-foraged organic produce',
    shelfLife: '2–3 days once soft',
  },
  {
    id: 'prod-papaya',
    name: 'Red Lady Farm Papaya',
    slug: 'red-lady-farm-papaya',
    category: 'fruits',
    categoryName: 'Fresh Fruits',
    shortDescription: 'Luscious salmon-orange flesh with mild honey sweetness and silky texture.',
    description: 'Tree-ripened on organic dwarf trees in Shadnagar. Loaded with papain enzymes that soothe digestion and revitalise skin health.',
    price: 65,
    originalPrice: 80,
    unit: '1 piece (~1.2 - 1.5 kg)',
    image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Tree Ripened Yesterday',
    originLocation: 'Shadnagar Agri Fields, Telangana',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Digestive Papain', 'Lycopene & Vitamin A', 'Immune Defense'],
    farmingMethod: 'Bee-pollinated organic orchard',
    shelfLife: '4–5 days',
  },
  {
    id: 'prod-coriander-mint',
    name: 'Aromatic Herb Duo (Coriander & Pudina)',
    slug: 'aromatic-herb-duo-coriander-mint',
    category: 'greens',
    categoryName: 'Leafy Greens',
    shortDescription: 'Fragrant desi cilantro and invigorating spearmint with roots kept intact.',
    description: 'Delivered in chilled breathable parchment to lock in essential oils. Essential for Hyderabadi biryanis, refreshing raitas, and evening green chutneys.',
    price: 35,
    originalPrice: 45,
    unit: 'Combo (1 bunch each)',
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Picked at Dawn',
    originLocation: 'Moinabad Herbal Farms, Telangana',
    availableLocations: ['hyderabad', 'secunderabad'],
    nutritionalHighlights: ['Digestive Oils', 'Detoxifying Chlorophyll', 'Vitamin C'],
    farmingMethod: 'Natural mulch beds & vermicompost',
    shelfLife: '5 days in damp wrap',
  },
  {
    id: 'prod-shimla-apples',
    name: 'Crisp Kinnaur Apples',
    slug: 'crisp-kinnaur-apples',
    category: 'fruits',
    categoryName: 'Fresh Fruits',
    shortDescription: 'Wax-free, naturally sweet mountain apples with a delightful snappy crunch.',
    description: 'Sourced from smallholder organic orchards in Kinnaur at 9,000 ft altitude. No chemical waxes or shine sprays—just pure Himalayan crunch.',
    price: 195,
    originalPrice: 240,
    unit: '1 kg (~5-6 apples)',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: true,
    isSeasonal: true,
    harvestDate: 'Cold Chain Transit from Himachal',
    originLocation: 'Kinnaur Valley, Himachal Pradesh',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Pectin Fiber', 'Quercetin Antioxidant', 'Heart Friendly'],
    farmingMethod: 'Glacier water irrigation & bio-dynamic compost',
    shelfLife: '14 days chilled',
  },
  {
    id: 'prod-bitter-gourd',
    name: 'Desi Small Bitter Gourd (Karela)',
    slug: 'desi-small-bitter-gourd-karela',
    category: 'vegetables',
    categoryName: 'Fresh Vegetables',
    shortDescription: 'Tender spiky gourds revered for natural blood-sugar balancing properties.',
    description: 'Naturally bitter and tender with minimal seeds. Perfect for stuffed bharwan karela or light stir fry with organic turmeric.',
    price: 42,
    originalPrice: 50,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Morning Harvest',
    originLocation: 'Nalgonda Organic Cluster, Telangana',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Charantin Compound', 'Metabolism Support', 'Purifies Blood'],
    farmingMethod: 'Trellis cultivation with natural cow-urine bio-repellent',
    shelfLife: '5–6 days',
  },
  {
    id: 'prod-lemons',
    name: 'Juicy Farm Lemons (Desi Nimbu)',
    slug: 'juicy-farm-lemons-desi-nimbu',
    category: 'fruits',
    categoryName: 'Fresh Fruits',
    shortDescription: 'Thin-skinned, highly aromatic yellow lemons overflowing with tangy juice.',
    description: 'Handpicked from mature citrus trees. An essential staple for daily hydration, salads, and South Indian rasams.',
    price: 35,
    originalPrice: 45,
    unit: 'Pack of 6 (~250g)',
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Yesterday Afternoon',
    originLocation: 'Rangareddy District, Telangana',
    availableLocations: ['hyderabad', 'secunderabad', 'warangal'],
    nutritionalHighlights: ['Pure Vitamin C', 'Alkalizing Citric Acid', 'Electrolytes'],
    farmingMethod: 'Natural rain-fed grove cultivation',
    shelfLife: '10–12 days',
  },
  {
    id: 'prod-methi',
    name: 'Fresh Fenugreek Greens (Methi Leaves)',
    slug: 'fresh-fenugreek-greens-methi',
    category: 'greens',
    categoryName: 'Leafy Greens',
    shortDescription: 'Fragrant young fenugreek shoots with delicate, appetizing bitterness.',
    description: 'Harvested while the stems remain tender and succulent. Adds deep culinary nuance to aloo methi, dal, and thepla.',
    price: 28,
    originalPrice: 35,
    unit: '1 bunch (~200g)',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    ],
    inStock: true,
    isOrganic: true,
    isFeatured: false,
    isSeasonal: false,
    harvestDate: 'Morning Harvest Today',
    originLocation: 'Chevella Farms, Telangana',
    availableLocations: ['hyderabad', 'secunderabad'],
    nutritionalHighlights: ['Soluble Fiber', 'Galactagogue Properties', 'Iron & Calcium'],
    farmingMethod: 'Zero chemical fertilizer Vedic cultivation',
    shelfLife: '3–4 days chilled',
  },
];

export const initialReviews: CustomerReview[] = [
  {
    id: 'rev-1',
    name: 'Ananya Sharma',
    location: 'Jubilee Hills, Hyderabad',
    rating: 5,
    title: 'Authentic heirloom taste, exactly like childhood summers!',
    comment:
      'The difference in taste is unbelievable. The Naatu tomatoes actually have that authentic tartness and aroma our grandmothers talk about, and the baby palak stayed fresh for five full days without wilting. Ordering directly on WhatsApp without login passwords is so refreshing!',
    date: 'September 28, 2026',
    verifiedPurchase: true,
    productName: 'Organic Country Tomatoes (Naatu Tomato)',
    helpfulCount: 42,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-2',
    name: 'K. S. Narayana',
    location: 'Gachibowli, Hyderabad',
    rating: 5,
    title: 'Lifesaver for diabetic nutrition & senior family members',
    comment:
      'As someone managing diabetes, finding genuinely chemical-free bitter gourd, fenugreek greens, and seasonal Deccan custard apples delivered early morning is a blessing. Vikrshi Suppliers is doing transparent, honest agriculture in Telangana.',
    date: 'September 25, 2026',
    verifiedPurchase: true,
    productName: 'Desi Small Bitter Gourd (Karela)',
    helpfulCount: 38,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-3',
    name: 'Dr. Priya Vangala',
    location: 'Banjara Hills, Hyderabad',
    rating: 5,
    title: 'Visited the Chevella farm with my kids — 100% genuine organic!',
    comment:
      'I visited their partner farm in Chevella on a weekend tour with my kids. Seeing the zero-pesticide methods and cow-based Jeevamrutham composting first-hand gave me complete peace of mind as a doctor and mother. We order weekly farm crates now.',
    date: 'September 20, 2026',
    verifiedPurchase: true,
    productName: 'Crunchy Ooty Carrots',
    helpfulCount: 56,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-4',
    name: 'Rajeshwari V.',
    location: 'Kondapur, Hyderabad',
    rating: 5,
    title: 'Greens stay fresh for 6 days without turning slimy',
    comment:
      'Supermarket greens usually turn slimy within 48 hours because they are treated with chemical water washes. Vikrshi greens arrive damp, crisp, and alive. The baby palak and methi made the most vibrant dals.',
    date: 'September 16, 2026',
    verifiedPurchase: true,
    productName: 'Tender Baby Palak (Spinach)',
    helpfulCount: 29,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-5',
    name: 'Rohit Mukerjee',
    location: 'Hitec City, Hyderabad',
    rating: 5,
    title: 'Delivered at 7:15 AM before I left for work',
    comment:
      'Living in Hitec City, getting farm-fresh produce delivered before 7:30 AM is invaluable. The tricolor bell peppers and Kinnaur apples are crunchy, wax-free, and taste clean. The WhatsApp team is remarkably responsive.',
    date: 'September 11, 2026',
    verifiedPurchase: true,
    productName: 'Farm-Fresh Tricolor Bell Peppers',
    helpfulCount: 19,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-6',
    name: 'S. Srinivas Rao',
    location: 'West Marredpally, Secunderabad',
    rating: 4,
    title: 'Top-tier quality produce and eco-friendly jute packing',
    comment:
      'Extremely impressed by the zero-plastic packaging in breathable jute and brown paper. Produce quality is 10/10. Only minor request is to add Sunday afternoon delivery slots in Secunderabad.',
    date: 'September 08, 2026',
    verifiedPurchase: true,
    productName: 'Ruby Red Organic Pomegranate (Anar)',
    helpfulCount: 14,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-7',
    name: 'Kavitha Reddy',
    location: 'Financial District, Hyderabad',
    rating: 5,
    title: 'Wild Sitaphal is out of this world!',
    comment:
      'The wild custard apples foraged from Ananthagiri hills are simply heavenly! Velvety, incredibly fragrant, and ripened on trees with zero calcium carbide. You cannot find this quality in commercial supermarkets.',
    date: 'September 04, 2026',
    verifiedPurchase: true,
    productName: 'Forest Custard Apple (Wild Sitaphal)',
    helpfulCount: 33,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'rev-8',
    name: 'Dr. Arun Teja',
    location: 'Tellapur, Hyderabad',
    rating: 5,
    title: 'Zero pesticide residue tested — highly recommended',
    comment:
      'As a healthcare researcher, knowing that groundwater runoff and crop soil are tested biannually for pesticide residues gives me confidence. Every household in Hyderabad should switch to Vikrshi.',
    date: 'August 29, 2026',
    verifiedPurchase: true,
    productName: 'Aromatic Herb Duo (Coriander & Pudina)',
    helpfulCount: 47,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
  },
];

export const instagramPosts = [
  {
    id: 'ig-1',
    imageUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
    caption: 'Dawn at the Chevella organic farm. The soil smells alive after morning dew. 🌿 #VikrshiFarms #OrganicHyderabad',
    likes: 342,
    date: 'Yesterday',
  },
  {
    id: 'ig-2',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    caption: 'Today’s harvest crate headed to Jubilee Hills and Kondapur families. Pure goodness without single drop of chemicals. 🥕🍅',
    likes: 419,
    date: '2 days ago',
  },
  {
    id: 'ig-3',
    imageUrl: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=600&q=80',
    caption: 'Wild Sitaphal season is here! Sourced ethically with forest dweller collectives in Ananthagiri Hills. 🍃',
    likes: 588,
    date: '3 days ago',
  },
  {
    id: 'ig-4',
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
    caption: 'Healthy soil = nutrient dense food. Checking our Jeevamrutham bio-culture vats with our lead agronomist. 🚜',
    likes: 275,
    date: '5 days ago',
  },
];

export const customerTestimonials = [
  {
    id: 't-1',
    name: 'Ananya Sharma',
    location: 'Jubilee Hills, Hyderabad',
    text: 'The difference in taste is unbelievable. The tomatoes actually have that authentic sourness our grandmothers talk about, and the palak stayed fresh for five days without wilting. Placing orders directly on WhatsApp is remarkably convenient!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 't-2',
    name: 'K. S. Narayana',
    location: 'Gachibowli, Hyderabad',
    text: 'As someone dealing with diabetes, getting chemical-free bitter gourd, methi, and wild custard apples delivered early morning is a blessing. Vikrshi Suppliers is doing honest, noble work for Hyderabad.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 't-3',
    name: 'Dr. Priya Vangala',
    location: 'Banjara Hills, Hyderabad',
    text: 'I visited their partner farm in Chevella on a weekend tour with my kids. Seeing the zero-pesticide methods and cow-based composting first-hand gave me complete peace of mind. We order weekly now.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  },
];
